[note]
language      = "en"
default-title = "Untitled"

[group.daily]
paths = ["journal"]

[group.daily.note]
filename = "{{ format-date now '%Y-%m-%d'}}"
extension = "md"
template = "daily.md"

[filter]
recents = "--sort created- --created-after 'last two weeks'"

[alias]
edlast = "zk edit --limit 1 --sort modified- $argv"

recent = "zk edit --sort created- --created-after 'last two weeks' --interactive"

ls = "zk edit --interactive" 

t = "zk edit --interactive --tag $argv"

config = 'c "$HOME/.dotfiles/zk/config.toml"'

daily = 'zk new --no-input "$ZK_NOTEBOOK_DIR/journal"'

ne = 'zk new --no-input "$ZK_NOTEBOOK_DIR/ideas" --title $argv'

journal = "zk edit --sort created- journal --interactive"

update = "cd $ZK_NOTEBOOK_DIR; git add -A; git commit -am 'updating'; git push; cd -"

rm = "zk list --interactive --quiet --format path --determine0 $argv | xargs -0 rm -vf --"

