git:
  pagers:
    - colorArg: always
      pager: diff-so-fancy
customCommands:
  - key: "G"
    description: "Open file at commit in browser"
    command: "zsh -c 'source ~/.config/zsh/aliases.zsh && g {{if .SelectedSubCommit}}{{.SelectedSubCommit.Hash}}{{else}}{{.SelectedLocalCommit.Hash}}{{end}} {{.SelectedCommitFile.Name}}'"
    context: "commitFiles"
  - key: "G"
    description: "Open branch in browser"
    command: "zsh -c 'source ~/.config/zsh/aliases.zsh && g {{.SelectedLocalBranch.Name}}'"
    context: "localBranches"
  - key: "G"
    description: "Open branch in browser"
    command: "zsh -c 'source ~/.config/zsh/aliases.zsh && g {{.SelectedRemoteBranch.Name}}'"
    context: "remoteBranches"
  - key: "G"
    description: "Open commit in browser"
    command: "zsh -c 'source ~/.config/zsh/aliases.zsh && g {{.SelectedSubCommit.Hash}}'"
    context: "subCommits"
  - key: "G"
    description: "Open commit in browser"
    command: "zsh -c 'source ~/.config/zsh/aliases.zsh && g {{.SelectedLocalCommit.Hash}}'"
    context: "commits"
  - key: "G"
    description: "Open current branch in browser"
    command: "zsh -c 'source ~/.config/zsh/aliases.zsh && g {{.CheckedOutBranch.Name}}'"
    context: "status"
  - key: "G"
    description: "Open repository in browser"
    command: "zsh -c 'source ~/.config/zsh/aliases.zsh && g'"
    context: "global"
